// Generated by build.rs (prost + tonic) into OUT_DIR as detcp.v1.rs
pub mod pb {
    include!(concat!(env!("OUT_DIR"), "/detcp.v1.rs"));
}

pub use pb::edge_sync_service_client::EdgeSyncServiceClient;
pub use pb::{SyncResponse, TelemetryBatch, TelemetryPoint};
